name: terraform-lint-validate

on:
  workflow_call:
    inputs:
      path:
        description: 'Path to the Terraform configuration directory'
        required: false
        type: string
        default: '.'

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    name: Check Terraform Formatting
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Terraform Formatting
        uses: dflook/terraform-fmt-check@v2
        with:
          path: ${{ inputs.path }}

  validate:
    runs-on: ubuntu-latest
    name: Validate Terraform Configuration
    needs: fmt-check
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Terraform Configuration
        uses: dflook/terraform-validate@v2
        with:
          path: ${{ inputs.path }}
